FROM python:3.7.6-slim-stretch
RUN mkdir app
WORKDIR /app

ENV PATH="${PATH}:/root/.local/bin"
ENV PYTHONPATH=.
RUN pip install --upgrade pip
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN ls
